### ISSUE TITLE
Convert Links To Normal Text and maybe for social media as users handle 

### ISSUE THREAD

**Issue by Hamdysaad20** [DragonsEG/RESUME-BUILDER#18]
![Screenshot 2023-10-23 212610](https://github.com/DragonsEG/RESUME-BUILDER/assets/73494683/093f791e-5664-42ec-982f-5f8a57ac1ef1)

# Important 🤯 
- Avoid including links on your resume as it can violate company policies and pose a security risk for employers.
- Convert any links to normal text that can be easily copied from a downloaded PDF.
- Use your social media handle or username instead of the full link to make your resume shorter and more readable.
- Note that including social media information is only relevant if you are an independent developer.
- add the social media logo with just the handle (if the handle provided show the icon )
- make sure that the handle is right and add error messages for it.

**Comment by AhmedhusseinENG** [comment]
for component resume 
// Resume.js
import React from 'react';

const Resume = ({ resumeText }) => {
  const convertLinksAndSocialMedia = (text) => {
    // Regular expression to match URLs
    const urlPattern = /http[s]?:\/\/(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+/g;

    // Regular expression to match social media handles (assuming they start with @)
    const socialMediaPattern = /@(\w+)/g;

    // Find all URLs in the text
    const urls = text.match(urlPattern);

    // Replace URLs with plain text
    if (urls) {
      urls.forEach((url) => {
        text = text.replace(url, 'Link');
      });
    }

    // Find all social media handles in the text
    const socialMediaHandles = text.match(socialMediaPattern);

    // Replace social media handles with plain text and add social media icons
    if (socialMediaHandles) {
      socialMediaHandles.forEach((handle) => {
        // Replace the handle with a social media icon and handle
        const replacement = `${handle} Icon`; // Replace 'Icon' with the actual icon you want to use
        text = text.replace(`@${handle}`, replacement);
      });
    }

    return text;
  };

  const processedResume = convertLinksAndSocialMedia(resumeText);

  return (
    <div>
      <pre>{processedResume}</pre>
    </div>
  );
};

export default Resume;
 

in App 
// import { useState } from 'react'
// import './App.css'
import React from 'react';
import Resume from './Resume';

function App() {
  const resumeText = `
  Check out my GitHub profile: https://github.com/username
  Follow me on Twitter: @twitter_handle
  Connect with me on LinkedIn: https://www.linkedin.com/in/yourname
`;
  return (
    
    <div>
      <h1> Enter Your Resume</h1>
      <Resume resumeText={resumeText} />
    </div>
    
  )
}

export default App
