### ISSUE TITLE
Hobbies Section

### ISSUE THREAD

**Issue by DarkCode662432** [DragonsEG/RESUME-BUILDER#9]
# Details:

- ### Build a component where the user can input their hobbies or interests.

___

**Comment by moamed018** [comment]
#12 
Hobbies section:
Allows the user to enter the hobby name and icon
It automatically starts with one hobby, and other hobbies can be added via the Add New Hobbies button
If the Show on Console button is pressed, the data will be displayed in object form on the console

Library used
"emoji-picker-react": "^4.5.2",
